title : 游离子
tagline: We are tossed by the waves of pain and tears.
author :
  name : 游离子
  email : lasteth@gmail.com
  github : lasteth
  twitter : 游离子
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
